channel: stable
addons:
  adguard:
    repository: markussiebert/homeassistant-addon-vzlogger
    target: vzlogger
    image: ghcr.io/markussiebert/homeassistant-addon-vzlogger/{arch}
  homeddns:
    repository: markussiebert/homeddns
    target: homeddns
    image: ghcr.io/markussiebert/homeddns
